package com.formkiq.idc.syntax;

public enum TokenType {
	ASSIGNMENT_OPERATOR, IDENTIFIER, KEYWORD, LEXEMES, NUMBER, QUOTE, RELATIONAL_OPERATOR, SQUARE_BRACKET_LEFT, SQUARE_BRACKET_RIGHT, WHITESPACE;
}
