version: "3.7"

services:

  ui:
    build: 
      context: ./ui
      args:
        NGINX_CONFIG: nginx-dev.conf
    depends_on:
      - api
    ports:
      - 80:80

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  apiml:
    build: ./api_ml
    environment:
      - STORAGE_DIRECTORY=/app/documents
    ports:
      - 5000:5000
    volumes:
      - documents:/app/documents

  api:
    build: ./idc
    depends_on:
      - elasticsearch
      - apiml
      - kafka
    environment:
      - storage.directory=/app/documents
      - elasticsearch.url=http://elasticsearch:9200
      - api.ml.url=http://apiml:5000
      - kafka.bootstrap.servers=http://kafka:29092
      - api.username=admin
      - api.password=password
    ports:
      - 8080:8080
    volumes:
      - documents:/app/documents

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch

volumes:
  documents:
  elasticsearch-data:
