micronaut:
  application:
    name: api
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:JiaNVpgPmpNNPrNaRwdsgtaKnzNarJur}
netty:
  default:
    allocator:
      max-order: 3