micronaut:
  application:
    name: api
  server:
    max-request-size: '100MB'
    multipart:
        max-file-size: '100MB'
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:JiaNVpgPmpNNPrNaRwdsgtaKnzNarJur}

netty:
  default:
    allocator:
      max-order: 3

kafka:
  consumers:
    default:
      max:
        poll:
          interval:
            ms: 3600000	

